development:
  adapter: postgresql
  database: wev_dev
  username: web
  password: 
  host: localhost

test:
  adapter: postgresql
  database: wev_test
  username: web
  password: 

production:
  adapter: postgresql
  database: wev_live
  username: web
  password: juminnoapps93
  host: http://juminnoapps.com


